#!/bin/bash
# this program will start printing from 1, having difference of 10 upto 100 

for var_name in $(seq 1 10  100); do
  echo "Counting $var_name..."
done


#output:
#Counting 1...
#Counting 11...
#Counting 21...
#Counting 31...
#Counting 41...
#Counting 51...
#Counting 61...
#Counting 71...
#Counting 81...
#Counting 91...


